#!/bin/sh

echo "Running mock cert provisioner startup script."

if [ $CI == "true" ]
  then
    export MOCK_CERT_PROVISIONER_SERVER_KEY=$MOCK_CERT_PROVISIONER_SERVER_KEY
    export MOCK_CERT_PROVISIONER_SERVER_CERT=$MOCK_CERT_PROVISIONER_SERVER_CERT
    export MOCK_CERT_PROVISIONER_ROOT_CERT=$MOCK_CERT_PROVISIONER_ROOT_CERT
  else
    export MOCK_CERT_PROVISIONER_SERVER_CERT="/services/localhost.crt"
    export MOCK_CERT_PROVISIONER_SERVER_KEY="/services/localhost.key"
    export MOCK_CERT_PROVISIONER_ROOT_CERT="/services/ca.crt"
fi

node /services/mockCertProvisionerApi.js