#!/bin/sh

echo "Running start control plane script"

export EV_APP_UUID=app_12345678
export EV_TEAM_UUID=team_12345678
export EV_CAGE_NAME=test-cage
export CAGE_UUID=cage_123456
export EV_CAGE_VERSION_ID=10
export ACME_S3_BUCKET="cages-acme-local"
export ACME_ACCOUNT_HMAC_KEY="cGxhY2Vob2xkZXI" # base64 url encoded "placeholder"
export ACME_ACCOUNT_HMAC_KEY_ID="placeholder_id"

export CERT_PROVISIONER_MTLS_CLIENT_CERT=$MOCK_CERT_PROVISIONER_CLIENT_CERT
export CERT_PROVISIONER_MTLS_CLIENT_KEY=$MOCK_CERT_PROVISIONER_CLIENT_KEY
export CERT_PROVISIONER_MTLS_ROOT_CERT=$MOCK_CERT_PROVISIONER_ROOT_CERT
export ACME_ACCOUNT_EC_KEY=$ACME_ACCOUNT_EC_KEY
export EXTERNAL_METRICS_ENABLED="true"
export STATS_BUFFER_SIZE=128

exec $CONTROL_PLANE_EXECUTABLE_PATH

