#!/bin/sh

echo "Running start control plane script"

export EV_APP_UUID=app_12345678
export EV_TEAM_UUID=team_12345678
export EV_CAGE_NAME=test-cage
export CAGE_UUID=cage_123456
export EV_CAGE_VERSION_ID=10

if [ $CI == "true" ]
  then
    export CERT_PROVISIONER_MTLS_CLIENT_CERT=$MOCK_CERT_PROVISIONER_CLIENT_CERT
    export CERT_PROVISIONER_MTLS_CLIENT_KEY=$MOCK_CERT_PROVISIONER_CLIENT_KEY
    export CERT_PROVISIONER_MTLS_ROOT_CERT=$MOCK_CERT_PROVISIONER_ROOT_CERT
  else
    export CERT_PROVISIONER_MTLS_CLIENT_CERT=$(cat $CONTROL_PLANE_SERVICE_PATH/client_0.crt)
    export CERT_PROVISIONER_MTLS_CLIENT_KEY=$(cat $CONTROL_PLANE_SERVICE_PATH/client_0.key)
    export CERT_PROVISIONER_MTLS_ROOT_CERT=$(cat $CONTROL_PLANE_SERVICE_PATH/ca.crt)
fi

exec $CONTROL_PLANE_EXECUTABLE_PATH

