#!/bin/sh

echo "Running start control plane script"

export EV_APP_UUID=app_12345678
export EV_TEAM_UUID=team_12345678
export EV_CAGE_NAME=test-cage
export CAGE_UUID=cage_123456
export EV_CAGE_VERSION_ID=10
export ACME_S3_BUCKET="test-ev-cages-acme-bucket.us-east-1s3.amazonaws.com"

export CERT_PROVISIONER_MTLS_CLIENT_CERT=$MOCK_CERT_PROVISIONER_CLIENT_CERT
export CERT_PROVISIONER_MTLS_CLIENT_KEY=$MOCK_CERT_PROVISIONER_CLIENT_KEY
export CERT_PROVISIONER_MTLS_ROOT_CERT=$MOCK_CERT_PROVISIONER_ROOT_CERT

exec $CONTROL_PLANE_EXECUTABLE_PATH

