on:
  push:
    paths:
      - crates/**
      - .github/workflows/lint.yml
name: Lint
permissions:
  contents: read
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install MUSL Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          targets: x86_64-unknown-linux-musl
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "standard-cache"
      - name: Check formatting
        run: cargo fmt --check
      - name: Clippy
        uses: clechasseur/rs-clippy-check@9190480d27706dc2fd75d122753936cafafa2154 # v6.0.1
        with:
          args: --features enclave -- -D warnings
      - name: Clippy check not enclave
        uses: clechasseur/rs-clippy-check@9190480d27706dc2fd75d122753936cafafa2154 # v6.0.1
        with:
          args: --features not_enclave -- -D warnings
