on:
  push:
    paths:
      - shared/**
      - .github/workflows/test-shared-lib.yml
      - Cargo.lock
name: Test Shared Library
jobs:
  test_shared_lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MUSL Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - uses: dtolnay/rust-toolchain@1.79.0
        with:
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "standard-cache"
      - name: Compile project
        run: cargo check -p shared --no-default-features --features network_egress
      - name: Test project
        run: cargo test -p shared --no-default-features --features network_egress
