on:
  push:
    paths:
      - src/**
      - .github/workflows/lint-and-test.yml
name: Lint and Test

permissions:
  contents: read

jobs:
  lint_and_test_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install latest stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo check -p storage-client-interface
        env:
          RUST_BACKTRACE: full