on:
  push:
    paths:
      - crates/data-plane/**
      - crates/shared/**
      - .github/workflows/test-data-plane.yml
      - Cargo.lock
permissions:
  contents: read
name: Test Data Plane
jobs:
  check_data_plane:
    strategy:
      matrix:
        feature-flags:
          [
            "tls_termination,enclave",
            "tls_termination,not_enclave",
            "enclave",
            "not_enclave",
            "tls_termination,enclave,network_egress",
            "tls_termination,not_enclave,network_egress",
            "enclave,network_egress",
            "not_enclave,network_egress",
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install MUSL Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "standard-cache"
      - name: Compile project with features ${{ matrix.feature-flags }}
        run: cargo check -p data-plane --no-default-features --features ${{ matrix.feature-flags }}

  test_data_plane:
    needs: [check_data_plane]
    strategy:
      matrix:
        feature-flags:
          [
            "not_enclave",
            "not_enclave,network_egress",
            "not_enclave,tls_termination",
            "not_enclave,tls_termination,network_egress",
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install MUSL Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "standard-cache"
      - name: Test project with features ${{ matrix.feature-flags }}
        run: cargo test -p data-plane --no-default-features --features ${{ matrix.feature-flags }}
      - name: Test project with features ${{ matrix.feature-flags }} using staging flag
        run: cargo test -p data-plane --no-default-features --features ${{ matrix.feature-flags }}
        env:
          RUSTFLAGS: "--cfg staging"
