on:
  push:
    paths:
      - shared/**
      - .github/workflows/test-shared-lib.yml
      - Cargo.lock
permissions:
  contents: read
name: Test Shared Library
jobs:
  test_shared_lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install MUSL Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          targets: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "standard-cache"
      - name: Compile project
        run: cargo check -p shared --no-default-features --features network_egress
      - name: Test project
        run: cargo test -p shared --no-default-features --features network_egress
